### ISSUE TITLE
Showcase page not working

### ISSUE THREAD

**Issue by lmsutools** [Emperorlou/MidJourneyTools#4]
Hi! Can you please make it work as well on https://www.midjourney.com/showcase/ ?
Currently it seems only working on https://www.midjourney.com/app/*

Perhaps you could also implement downloading upscaled images by fetching them from the api:
https://www.midjourney.com/api/public-feed/?orderBy=hot
https://www.midjourney.com/api/public-feed/?orderBy=top

Thanks.

**Comment by Emperorlou** [comment]
I should be able to make it work in the showcase

**Comment by Emperorlou** [comment]
Version 1.3.1 should now work in the /showcase page.
